### ISSUE TITLE
`CancellationToken` in templates

### ISSUE THREAD

**Issue by Tyrrrz** [ltrzesniewski/RazorBlade#2]
Hi!

It would be nice to have some sort of `CancellationToken` inside a template, that you can pass by calling `Render()` or `RenderAsync()`.

The motivation is such that a template may invoke async methods that support cancellation, so it could be nice to propagate a token during rendering.

In MiniRazor, I just exposed a `CancellationToken` property:

https://github.com/Tyrrrz/MiniRazor/blob/c83bf8b9d4ed1d07dc4a377b30b308f6cecc44e2/MiniRazor.Runtime/TemplateBase.cs#L27-L28

Which is set when calling `RenderAsync()`:

https://github.com/Tyrrrz/MiniRazor/blob/c83bf8b9d4ed1d07dc4a377b30b308f6cecc44e2/MiniRazor.CodeGen/TemplateClassGenerator.cs#L95-L103

**Comment by ltrzesniewski** [comment]
Hi!

That's a good idea. Adding a `CancellationToken` property and a `RenderAsync` overload/default argument makes sense. I suppose I should also add this to `Render` for parity's sake.

In the meantime, you can work around the lack of this feature by adding the property to the template, or by creating an intermediate base class. It's a bit cumbersome though.

```razor
@functions
{
	public CancellationToken CancellationToken { get; init; }
}
```

**Comment by Tyrrrz** [comment]
That's a good workaround, thanks!

**Comment by ltrzesniewski** [comment]
This is released in https://github.com/ltrzesniewski/RazorBlade/releases/tag/v0.3.0
