### ISSUE TITLE
Cannot use RazorBlade in a roslyn SourceGenerator, because it requires C# 10, and source generators need to target netstandard2.0 which only has c# 7.3

### ISSUE THREAD

**Issue by ghost** [ltrzesniewski/RazorBlade#7]
Please make it support netstandard too.

I created a fork, I will try to implement this myself, thanx.

**Comment by ltrzesniewski** [comment]
Maybe I should document this, but you can add the following to your source generator's csproj:

```xml
<PropertyGroup>
  <LangVersion>11.0</LangVersion>
</PropertyGroup>
```

And it will work. 🙂 

I don't want to downgrade the whole library code to C# 7.3 TBH.

**Comment by ghost** [comment]
You're right, this works fine, thank you.
